replicaCount: 2

image:
  repository: ghcr.io/chacky13/ecommerce-app
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

database:
  host: "db-service"
  password: "superpassword123"