name: Lab 3 K8s Deployment

on:
  push:
    branches: [ lab3 ]

jobs:
  k8s-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build Docker image locally
        run: |
          docker build -t ghcr.io/chacky13/ecommerce-app:latest .


      - name: Create KinD cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind


      - name: Load image into KinD
        run: |
          kind load docker-image ghcr.io/chacky13/ecommerce-app:latest --name kind


      - name: Apply K8s manifests
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml


      - name: Wait for pods
        run: sleep 15


      - name: Run Master Validation Script
        run: |
          chmod +x ./tests/lab3_test.sh
          ./tests/lab3_test.sh