name: Lab 3 K8s Deployment

on:
  push:
    branches: [ lab3 ]

jobs:
  k8s-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Створюємо кластер KinD (Kubernetes in Docker)
      - name: Create KinD cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind

      # Застосовуємо наші маніфести
      - name: Apply K8s manifests
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # Чекаємо трохи, поки поди піднімуться, і запускаємо тест
      - name: Run Master Validation Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./tests/lab3_test.sh
          ./tests/lab3_test.sh